version: 0.2

env:
  variables:
    PACKAGE: "forex"
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      # Download the appropriate version of the Fabric Shim
      - wget https://github.com/hyperledger/fabric/archive/v1.4.2.tar.gz
      - tar xvzf v1.4.2.tar.gz
      - mkdir -p /go/src/github.com/hyperledger
      - mv fabric-1.4.2 /go/src/github.com/hyperledger/fabric
      - rm v1.4.2.tar.gz
      
      # Install golint
      - go get -u github.com/golang/lint/golint
  build:
    commands:
      - mkdir -p /go/src/${PACKAGE}
      - ls /go/src/forex
      - ls ${CODEBUILD_SRC_DIR}

      - cp -r ${CODEBUILD_SRC_DIR}/* /go/src/${PACKAGE}/

      - cd /go/src/${PACKAGE}

      - go get -t .
      
      # Lint our Chaincode 
      - golint -set_exit_status

      # Check the Go code for common problems with 'go vet'
      - go vet .

      # Run unit tests using Mockshim to test our chaicode
      - go test .

      - zip -r  /go/src/${PACKAGE}/forex.zip "/go/src/${PACKAGE}"


artifacts:
  files:
     - /go/src/${PACKAGE}/forex.zip
